# Generated by Django 5.1.2 on 2024-11-27 21:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_category_options_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Descuento'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio'),
            preserve_default=False,
        ),
    ]
